language: ruby
rvm:
  - 2.6.2
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
before_script:
  - cp config/database.yml.sample config/database.yml
  - RAILS_ENV=test bundle exec rails webpacker:compile