language: ruby

rvm:
  - 2.6.2

cache:
  bundler: true
  directories:
    - node_modules

before_script:
  - cp config/database.yml.sample config/database.yml
  - bundle exec rails webpacker:compile

script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec

before_install:
  - gem update --system
  - gem install bundler

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn